/*=============================================================
  FROSTBYTE SKI SUPPLY INVENTORY — Infrastructure Setup
  
  Naming convention:
    Database:   FROSTBYTE_INVENTORY
    Schemas:    RAW | HARMONIZED | ANALYTICS
    Warehouse:  FROSTBYTE_INVENTORY_WH
    Roles:      FROSTBYTE_INVENTORY_ADMIN
                FROSTBYTE_INVENTORY_TRANSFORM
                FROSTBYTE_INVENTORY_ANALYST
=============================================================*/

USE ROLE ACCOUNTADMIN;

---------------------------------------------------------------
-- 1. DATABASE
---------------------------------------------------------------
CREATE DATABASE IF NOT EXISTS FROSTBYTE_INVENTORY
    COMMENT = 'Frostbyte ski supply inventory project';

---------------------------------------------------------------
-- 2. SCHEMAS
---------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS FROSTBYTE_INVENTORY.RAW
    COMMENT = 'Raw ingested data from source systems';

CREATE SCHEMA IF NOT EXISTS FROSTBYTE_INVENTORY.HARMONIZED
    COMMENT = 'Cleansed and conformed data';

CREATE SCHEMA IF NOT EXISTS FROSTBYTE_INVENTORY.ANALYTICS
    COMMENT = 'Business-ready models and aggregations';

---------------------------------------------------------------
-- 3. WAREHOUSE
---------------------------------------------------------------
CREATE WAREHOUSE IF NOT EXISTS FROSTBYTE_INVENTORY_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Compute for Frostbyte inventory workloads';

---------------------------------------------------------------
-- 4. ROLES
---------------------------------------------------------------
CREATE ROLE IF NOT EXISTS FROSTBYTE_INVENTORY_ADMIN
    COMMENT = 'Full control over inventory database objects';

CREATE ROLE IF NOT EXISTS FROSTBYTE_INVENTORY_TRANSFORM
    COMMENT = 'Read RAW, write to HARMONIZED and ANALYTICS';

CREATE ROLE IF NOT EXISTS FROSTBYTE_INVENTORY_ANALYST
    COMMENT = 'Read-only access to ANALYTICS schema';

---------------------------------------------------------------
-- 5. ROLE HIERARCHY
--    ACCOUNTADMIN
--      └── FROSTBYTE_INVENTORY_ADMIN
--            └── FROSTBYTE_INVENTORY_TRANSFORM
--                  └── FROSTBYTE_INVENTORY_ANALYST
---------------------------------------------------------------
GRANT ROLE FROSTBYTE_INVENTORY_ANALYST TO ROLE FROSTBYTE_INVENTORY_TRANSFORM;
GRANT ROLE FROSTBYTE_INVENTORY_TRANSFORM TO ROLE FROSTBYTE_INVENTORY_ADMIN;
GRANT ROLE FROSTBYTE_INVENTORY_ADMIN TO ROLE ACCOUNTADMIN;

---------------------------------------------------------------
-- 6. GRANTS — DATABASE
---------------------------------------------------------------
GRANT OWNERSHIP ON DATABASE FROSTBYTE_INVENTORY
    TO ROLE FROSTBYTE_INVENTORY_ADMIN
    REVOKE CURRENT GRANTS;

GRANT USAGE ON DATABASE FROSTBYTE_INVENTORY
    TO ROLE FROSTBYTE_INVENTORY_TRANSFORM;

GRANT USAGE ON DATABASE FROSTBYTE_INVENTORY
    TO ROLE FROSTBYTE_INVENTORY_ANALYST;

---------------------------------------------------------------
-- 7. GRANTS — SCHEMAS
---------------------------------------------------------------
-- ADMIN owns all schemas
GRANT OWNERSHIP ON ALL SCHEMAS IN DATABASE FROSTBYTE_INVENTORY
    TO ROLE FROSTBYTE_INVENTORY_ADMIN
    REVOKE CURRENT GRANTS;

-- TRANSFORM: full access to RAW, HARMONIZED, ANALYTICS
GRANT USAGE ON SCHEMA FROSTBYTE_INVENTORY.RAW
    TO ROLE FROSTBYTE_INVENTORY_TRANSFORM;
GRANT USAGE ON SCHEMA FROSTBYTE_INVENTORY.HARMONIZED
    TO ROLE FROSTBYTE_INVENTORY_TRANSFORM;
GRANT USAGE ON SCHEMA FROSTBYTE_INVENTORY.ANALYTICS
    TO ROLE FROSTBYTE_INVENTORY_TRANSFORM;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA FROSTBYTE_INVENTORY.RAW
    TO ROLE FROSTBYTE_INVENTORY_TRANSFORM;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA FROSTBYTE_INVENTORY.HARMONIZED
    TO ROLE FROSTBYTE_INVENTORY_TRANSFORM;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA FROSTBYTE_INVENTORY.ANALYTICS
    TO ROLE FROSTBYTE_INVENTORY_TRANSFORM;

-- Future grants for TRANSFORM on tables/views
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA FROSTBYTE_INVENTORY.RAW
    TO ROLE FROSTBYTE_INVENTORY_TRANSFORM;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA FROSTBYTE_INVENTORY.HARMONIZED
    TO ROLE FROSTBYTE_INVENTORY_TRANSFORM;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA FROSTBYTE_INVENTORY.ANALYTICS
    TO ROLE FROSTBYTE_INVENTORY_TRANSFORM;

-- ANALYST: read-only on ANALYTICS
GRANT USAGE ON SCHEMA FROSTBYTE_INVENTORY.ANALYTICS
    TO ROLE FROSTBYTE_INVENTORY_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA FROSTBYTE_INVENTORY.ANALYTICS
    TO ROLE FROSTBYTE_INVENTORY_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA FROSTBYTE_INVENTORY.ANALYTICS
    TO ROLE FROSTBYTE_INVENTORY_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FROSTBYTE_INVENTORY.ANALYTICS
    TO ROLE FROSTBYTE_INVENTORY_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FROSTBYTE_INVENTORY.ANALYTICS
    TO ROLE FROSTBYTE_INVENTORY_ANALYST;

---------------------------------------------------------------
-- 8. GRANTS — WAREHOUSE
---------------------------------------------------------------
GRANT OWNERSHIP ON WAREHOUSE FROSTBYTE_INVENTORY_WH
    TO ROLE FROSTBYTE_INVENTORY_ADMIN
    REVOKE CURRENT GRANTS;

GRANT USAGE, OPERATE ON WAREHOUSE FROSTBYTE_INVENTORY_WH
    TO ROLE FROSTBYTE_INVENTORY_TRANSFORM;

GRANT USAGE ON WAREHOUSE FROSTBYTE_INVENTORY_WH
    TO ROLE FROSTBYTE_INVENTORY_ANALYST;

---------------------------------------------------------------
-- Done! Verify with:
---------------------------------------------------------------
SHOW SCHEMAS IN DATABASE FROSTBYTE_INVENTORY;
SHOW GRANTS TO ROLE FROSTBYTE_INVENTORY_ADMIN;
SHOW GRANTS TO ROLE FROSTBYTE_INVENTORY_TRANSFORM;
SHOW GRANTS TO ROLE FROSTBYTE_INVENTORY_ANALYST;
